/******************************************************************************
 *  File:       console_flash_manager.h
 *  Author:     Callum Rafferty
 *  Created:    15-Aug-2026
 *
 *  Description:
 *      Console interface for staged External Flash and Flash Manager hardware
 *      bring-up.
 *
 *  Destructive hardware bring-up sequence:
 *
 *      `flash init`
 *      `flash status`
 *      `flash external_test [seed]`
 *      `flash upload_test [record_count] [seed]`
 *      `flash prepare`
 *      `flash execute_echo [100|1000|10000]`
 *      `flash finalise`
 *      `flash results verify`
 *
 *  `execute_echo` is the execution-facing API test. It temporarily redirects
 *  the existing priority-5 TIM4 interrupt away from the production Execution
 *  Manager and into a diagnostic callback. The callback processes the
 *  deterministic stream generated by upload_test and writes an identical
 *  packed result stream through the public Flash Manager FromISR APIs. It
 *  performs no NAND access or console output inside the ISR. The console task
 *  waits with periodic delays so the Flash Manager task can refill instruction
 *  pages and drain result pages concurrently.
 *
 *  Begin at 100 Hz. After a complete byte-for-byte result verification, repeat
 *  at 1 kHz and 10 kHz and increase the record count. A NOT_BUFFERED failure is
 *  an instruction-refill deadline miss; a reservation failure is a
 *  result-drain throughput failure; a past timestamp is an execution overrun.
 *
 *  TIM4 must not already be serving a production run. execute_echo stops TIM4
 *  before installing the diagnostic callback, stops it again on every terminal
 *  path, and restores the Execution Manager callback before returning. Only
 *  call `flash finalise` after execute_echo returns. On failure, inspect
 *  `flash status`, optionally retrieve partial results without `verify`, and
 *  reset before retrying.
 *
 *  End-of-instruction-stream terminates this diagnostic only; production test
 *  completion remains a separate Run State/Execution Manager policy. The echo
 *  validates storage and ISR/task handoff, not peripheral dispatch, real
 *  measurement acquisition, or worst-case execution timing.
 *
 *  The empty-result path is tested by omitting execute_echo after prepare,
 *  running finalise, and retrieving with `flash results` without `verify`.
 ******************************************************************************/

#ifndef CONSOLE_FLASH_MANAGER_H
#define CONSOLE_FLASH_MANAGER_H

#ifdef __cplusplus
extern "C"
{
#endif

/**-----------------------------------------------------------------------------
 *  Includes
 *------------------------------------------------------------------------------
 */

#include <stdint.h>

/**-----------------------------------------------------------------------------
 *  Public Function Prototypes
 *------------------------------------------------------------------------------
 */

/**
 * @brief Handles the staged External Flash and Flash Manager console commands.
 *
 * @param argc Number of command arguments.
 * @param argv Array of argument strings.
 */
void CONSOLE_FlashManager_Command( uint16_t argc, char* argv[] );

#ifdef __cplusplus
}
#endif

#endif /* CONSOLE_FLASH_MANAGER_H */
